"""Initial schema

Revision ID: 96c5a12c92d3
Revises: 
Create Date: 2025-11-25 16:47:57.652812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c5a12c92d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_v2_score', sa.Float(), nullable=True),
    sa.Column('cvss_v2_severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_severity', sa.String(length=20), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('modified_date', sa.Date(), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('cwe', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cve_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cve_cache_cve_id'), ['cve_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cve_cache_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_type', sa.Enum('PREDEFINED', 'CUSTOM', name='apitype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('supported_ioc_types', sa.JSON(), nullable=True),
    sa.Column('authentication_type', sa.Enum('API_KEY', 'BASIC_AUTH', 'BEARER_TOKEN', 'OAUTH', 'NONE', name='authenticationtype'), nullable=False),
    sa.Column('request_config', sa.JSON(), nullable=True),
    sa.Column('response_config', sa.JSON(), nullable=True),
    sa.Column('rate_limit_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_sources_name'), ['name'], unique=True)

    op.create_table('asset_watchlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_watchlist_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_watchlist_user_id'), ['user_id'], unique=False)

    op.create_table('ioc_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_value', sa.String(length=500), nullable=False),
    sa.Column('query_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ioc_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ioc_queries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ioc_queries_ioc_type'), ['ioc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ioc_queries_ioc_value'), ['ioc_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_ioc_queries_query_date'), ['query_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ioc_queries_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('PDF', 'HTML', 'JSON', name='reportformat'), nullable=False),
    sa.Column('shared_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_source_id', sa.String(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('update_mode', sa.Enum('MANUAL', 'AUTO', name='updatemode'), nullable=False),
    sa.Column('rate_limit', sa.String(length=100), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_status', sa.Enum('VALID', 'INVALID', 'NOT_TESTED', name='teststatus'), nullable=False),
    sa.Column('last_test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_source_id'], ['api_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_api_source_id'), ['api_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('asset_watchlist_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_threshold', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskthreshold'), nullable=True),
    sa.Column('last_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_risk_score', sa.String(length=50), nullable=True),
    sa.Column('last_status', sa.Enum('CLEAN', 'SUSPICIOUS', 'MALICIOUS', name='iocstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['asset_watchlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_watchlist_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_watchlist_items_ioc_type'), ['ioc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_watchlist_items_ioc_value'), ['ioc_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_watchlist_items_watchlist_id'), ['watchlist_id'], unique=False)

    op.create_table('threat_intelligence_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ioc_query_id', sa.String(), nullable=False),
    sa.Column('source_api', sa.String(length=100), nullable=False),
    sa.Column('raw_data_json', sa.JSON(), nullable=True),
    sa.Column('processed_data_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ioc_query_id'], ['ioc_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_intelligence_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_intelligence_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_intelligence_data_ioc_query_id'), ['ioc_query_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_intelligence_data_source_api'), ['source_api'], unique=False)

    op.create_table('asset_check_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_item_id', sa.String(), nullable=False),
    sa.Column('check_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('risk_score', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CLEAN', 'SUSPICIOUS', 'MALICIOUS', name='iocstatus'), nullable=True),
    sa.Column('threat_intelligence_data', sa.JSON(), nullable=True),
    sa.Column('sources_checked', sa.JSON(), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['asset_watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_check_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_check_history_check_date'), ['check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_check_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_check_history_watchlist_item_id'), ['watchlist_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_check_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_check_history_watchlist_item_id'))
        batch_op.drop_index(batch_op.f('ix_asset_check_history_id'))
        batch_op.drop_index(batch_op.f('ix_asset_check_history_check_date'))

    op.drop_table('asset_check_history')
    with op.batch_alter_table('threat_intelligence_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_intelligence_data_source_api'))
        batch_op.drop_index(batch_op.f('ix_threat_intelligence_data_ioc_query_id'))
        batch_op.drop_index(batch_op.f('ix_threat_intelligence_data_id'))

    op.drop_table('threat_intelligence_data')
    with op.batch_alter_table('asset_watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_watchlist_items_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_asset_watchlist_items_ioc_value'))
        batch_op.drop_index(batch_op.f('ix_asset_watchlist_items_ioc_type'))
        batch_op.drop_index(batch_op.f('ix_asset_watchlist_items_id'))

    op.drop_table('asset_watchlist_items')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_api_source_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('ioc_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_ioc_queries_query_date'))
        batch_op.drop_index(batch_op.f('ix_ioc_queries_ioc_value'))
        batch_op.drop_index(batch_op.f('ix_ioc_queries_ioc_type'))
        batch_op.drop_index(batch_op.f('ix_ioc_queries_id'))

    op.drop_table('ioc_queries')
    with op.batch_alter_table('asset_watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_watchlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_watchlist_id'))

    op.drop_table('asset_watchlist')
    with op.batch_alter_table('api_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_sources_name'))
        batch_op.drop_index(batch_op.f('ix_api_sources_id'))

    op.drop_table('api_sources')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('cve_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cve_cache_id'))
        batch_op.drop_index(batch_op.f('ix_cve_cache_cve_id'))

    op.drop_table('cve_cache')
    # ### end Alembic commands ###
