"""Initial schema

Revision ID: e1dd2875d480
Revises: 
Create Date: 2025-11-25 16:46:39.683159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1dd2875d480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_v2_score', sa.Float(), nullable=True),
    sa.Column('cvss_v2_severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_severity', sa.String(length=20), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('modified_date', sa.Date(), nullable=True),
    sa.Column('affected_products', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('cwe', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cve_cache_cve_id'), 'cve_cache', ['cve_id'], unique=True)
    op.create_index(op.f('ix_cve_cache_id'), 'cve_cache', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_type', sa.Enum('PREDEFINED', 'CUSTOM', name='apitype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('supported_ioc_types', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('authentication_type', sa.Enum('API_KEY', 'BASIC_AUTH', 'BEARER_TOKEN', 'OAUTH', 'NONE', name='authenticationtype'), nullable=False),
    sa.Column('request_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('response_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('rate_limit_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sources_id'), 'api_sources', ['id'], unique=False)
    op.create_index(op.f('ix_api_sources_name'), 'api_sources', ['name'], unique=True)
    op.create_table('asset_watchlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_watchlist_id'), 'asset_watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_asset_watchlist_user_id'), 'asset_watchlist', ['user_id'], unique=False)
    op.create_table('ioc_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_value', sa.String(length=500), nullable=False),
    sa.Column('query_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('results_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ioc_queries_id'), 'ioc_queries', ['id'], unique=False)
    op.create_index(op.f('ix_ioc_queries_ioc_type'), 'ioc_queries', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_ioc_queries_ioc_value'), 'ioc_queries', ['ioc_value'], unique=False)
    op.create_index(op.f('ix_ioc_queries_query_date'), 'ioc_queries', ['query_date'], unique=False)
    op.create_index(op.f('ix_ioc_queries_user_id'), 'ioc_queries', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('PDF', 'HTML', 'JSON', name='reportformat'), nullable=False),
    sa.Column('shared_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_source_id', sa.String(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('update_mode', sa.Enum('MANUAL', 'AUTO', name='updatemode'), nullable=False),
    sa.Column('rate_limit', sa.String(length=100), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_status', sa.Enum('VALID', 'INVALID', 'NOT_TESTED', name='teststatus'), nullable=False),
    sa.Column('last_test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_source_id'], ['api_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_source_id'), 'api_keys', ['api_source_id'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('asset_watchlist_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_threshold', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskthreshold'), nullable=True),
    sa.Column('last_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_risk_score', sa.String(length=50), nullable=True),
    sa.Column('last_status', sa.Enum('CLEAN', 'SUSPICIOUS', 'MALICIOUS', name='iocstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['asset_watchlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_watchlist_items_id'), 'asset_watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_asset_watchlist_items_ioc_type'), 'asset_watchlist_items', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_asset_watchlist_items_ioc_value'), 'asset_watchlist_items', ['ioc_value'], unique=False)
    op.create_index(op.f('ix_asset_watchlist_items_watchlist_id'), 'asset_watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('threat_intelligence_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ioc_query_id', sa.String(), nullable=False),
    sa.Column('source_api', sa.String(length=100), nullable=False),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('processed_data_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ioc_query_id'], ['ioc_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_data_id'), 'threat_intelligence_data', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_data_ioc_query_id'), 'threat_intelligence_data', ['ioc_query_id'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_data_source_api'), 'threat_intelligence_data', ['source_api'], unique=False)
    op.create_table('asset_check_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('watchlist_item_id', sa.String(), nullable=False),
    sa.Column('check_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('risk_score', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CLEAN', 'SUSPICIOUS', 'MALICIOUS', name='iocstatus'), nullable=True),
    sa.Column('threat_intelligence_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('sources_checked', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['asset_watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_check_history_check_date'), 'asset_check_history', ['check_date'], unique=False)
    op.create_index(op.f('ix_asset_check_history_id'), 'asset_check_history', ['id'], unique=False)
    op.create_index(op.f('ix_asset_check_history_watchlist_item_id'), 'asset_check_history', ['watchlist_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_check_history_watchlist_item_id'), table_name='asset_check_history')
    op.drop_index(op.f('ix_asset_check_history_id'), table_name='asset_check_history')
    op.drop_index(op.f('ix_asset_check_history_check_date'), table_name='asset_check_history')
    op.drop_table('asset_check_history')
    op.drop_index(op.f('ix_threat_intelligence_data_source_api'), table_name='threat_intelligence_data')
    op.drop_index(op.f('ix_threat_intelligence_data_ioc_query_id'), table_name='threat_intelligence_data')
    op.drop_index(op.f('ix_threat_intelligence_data_id'), table_name='threat_intelligence_data')
    op.drop_table('threat_intelligence_data')
    op.drop_index(op.f('ix_asset_watchlist_items_watchlist_id'), table_name='asset_watchlist_items')
    op.drop_index(op.f('ix_asset_watchlist_items_ioc_value'), table_name='asset_watchlist_items')
    op.drop_index(op.f('ix_asset_watchlist_items_ioc_type'), table_name='asset_watchlist_items')
    op.drop_index(op.f('ix_asset_watchlist_items_id'), table_name='asset_watchlist_items')
    op.drop_table('asset_watchlist_items')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_api_source_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_ioc_queries_user_id'), table_name='ioc_queries')
    op.drop_index(op.f('ix_ioc_queries_query_date'), table_name='ioc_queries')
    op.drop_index(op.f('ix_ioc_queries_ioc_value'), table_name='ioc_queries')
    op.drop_index(op.f('ix_ioc_queries_ioc_type'), table_name='ioc_queries')
    op.drop_index(op.f('ix_ioc_queries_id'), table_name='ioc_queries')
    op.drop_table('ioc_queries')
    op.drop_index(op.f('ix_asset_watchlist_user_id'), table_name='asset_watchlist')
    op.drop_index(op.f('ix_asset_watchlist_id'), table_name='asset_watchlist')
    op.drop_table('asset_watchlist')
    op.drop_index(op.f('ix_api_sources_name'), table_name='api_sources')
    op.drop_index(op.f('ix_api_sources_id'), table_name='api_sources')
    op.drop_table('api_sources')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cve_cache_id'), table_name='cve_cache')
    op.drop_index(op.f('ix_cve_cache_cve_id'), table_name='cve_cache')
    op.drop_table('cve_cache')
    # ### end Alembic commands ###
